// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using air_ticket_cashier;

namespace air_ticket_cashier.Migrations
{
    [DbContext(typeof(CashierContext))]
    [Migration("20200902155641_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("air_ticket_cashier.Direction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Avaliable")
                        .HasColumnType("boolean");

                    b.Property<int>("DirectionType")
                        .HasColumnType("integer");

                    b.Property<string>("FromCountry")
                        .HasColumnType("text");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<string>("PlaneCode")
                        .HasColumnType("text");

                    b.Property<string>("ToCountry")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("direction");
                });

            modelBuilder.Entity("air_ticket_cashier.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("ArriveAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DeparureAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DirectionID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DirectionID");

                    b.ToTable("flight");
                });

            modelBuilder.Entity("air_ticket_cashier.Flight", b =>
                {
                    b.HasOne("air_ticket_cashier.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionID");
                });
#pragma warning restore 612, 618
        }
    }
}
